remote_theme: b2a3e8/jekyll-theme-console
title: JLPT Senpai
icon: ./favicon.png
header_pages:
  - index.md
  - N5.md
  - about.md
style: dark
footer: 'project maintained by <a href="https://github.com/Devansh3712">devansh</a>'
