remote_theme: Devansh3712/jekyll-theme-console
title: JLPT Senpai
header_pages:
  - index.md
  - N5.md
  - about.md
style: dark
footer: 'project maintained by <a href="https://github.com/Devansh3712">devansh</a>'
